### PR TITLE
adding git ignore

### PR DESCRIPTION
**Pull request by AlhaythamElhassan**
I have just added a gitignore file

### CODE REVIEW

**Comment by isambard217** [comment]
[Learn about the transportation market](https://trello.com/c/yDIuTPPl/2-learn-about-the-transportation-market)

**Comment by isambard217** [comment]
[Learn about the transportation market](https://trello.com/c/yDIuTPPl/2-learn-about-the-transportation-market)

**Comment by isambard217** [comment]
[Learn about the transportation market](https://trello.com/c/yDIuTPPl/2-learn-about-the-transportation-market)

**Comment by isambard217** [comment]
[master branch](https://trello.com/c/orVfaMoj/1-master-branch)

**Comment by AlhaythamElhassan** [comment]
[Learn about the transportation market](https://trello.com/c/yDIuTPPl/2-learn-about-the-transportation-market)

**Comment by AlhaythamElhassan** [comment]
[Learn about the transportation market](https://trello.com/c/yDIuTPPl/2-learn-about-the-transportation-market)

**Pull request merged**
